@echo off
set RSM_HOME=C:\Program Files\MSquared\M2 RSM\
set EXE_RSM="%RSM_HOME%"\rsm.exe
%EXE_RSM% -X -O"RSM\pa2_001.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_001.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_002.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_002.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_003.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_003.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_004.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_004.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_005.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_005.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_006.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_006.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_007.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_007.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_008.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_008.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_009.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_009.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_010.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_010.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_011.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_011.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_012.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_012.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_013.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_013.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_014.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_014.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_015.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_015.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_016.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_016.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_017.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_017.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_018.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_018.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_019.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_019.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_020.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_020.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_021.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_021.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_022.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_022.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_023.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_023.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_024.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_024.cs.lst"
%EXE_RSM% -X -O"RSM\pa2_025.cs.xml" -S"Total All Metrics" -Ta -Tl -TN -F"C:\Documents and Settings\gjing\M2 RSM Wizard\input\pa2_025.cs.lst"
